site_name: 华师手册
copyright: Copyright © 2023-2024 华师手册
repo_url: https://github.com/SCNU-SW/SCNU-SW-Wiki
repo_name: SCNU-SW/SCNU-SW-Wiki
edit_uri: https://365369.xyz/edit-landing/?ref=


nav:
  - 简介:
    - Getting Started: index.md
  - 学习:
    - 生涯规划: learning/career.md
  - 工具软件:
    - 工具软件简介: tools/index.md
    - 代码编辑工具:
      - Vim: tools/editor/vim.md
      - Emacs: tools/editor/emacs.md
      - VS Code: tools/editor/vscode.md
      - Atom: tools/editor/atom.md
      - Eclipse: tools/editor/eclipse.md
      - Notepad++: tools/editor/npp.md
      - Kate: tools/editor/kate.md
      - Dev-C++: tools/editor/devcpp.md
      - CLion: tools/editor/clion.md
      - Geany: tools/editor/geany.md
      - Xcode: tools/editor/xcode.md
      - GUIDE: tools/editor/guide.md
      - Sublime Text: tools/editor/sublime.md
      - CP Editor: tools/editor/cpeditor.md
    - 评测工具: 
      - 评测工具简介: tools/judger/index.md
      - Arbiter: tools/judger/arbiter.md
      - Cena: tools/judger/cena.md
      - CCR Plus: tools/judger/ccr-plus.md
      - Lemon: tools/judger/lemon.md
    - 命令行: tools/cmd.md
    - 编译器: tools/compiler.md
    - WSL (Windows 10): tools/wsl.md
    - Special Judge: tools/special-judge.md
    - Testlib:
      - Testlib 简介: tools/testlib/index.md
      - 通用: tools/testlib/general.md
      - Generator: tools/testlib/generator.md
      - Validator: tools/testlib/validator.md
      - Interactor: tools/testlib/interactor.md
      - Checker: tools/testlib/checker.md
    - Polygon: tools/polygon.md
    - OJ 工具: tools/oj-tool.md
    - LaTeX 入门: tools/latex.md
    - Git: tools/git.md


theme:
  name: material
  custom_dir: overrides
  language: zh

  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil
  
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  logo: assets/scnu.png
  favicon: assets/scnu.png

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
    - content.action.edit

  font:
    text: Fira Sans
    code: Fira Mono


extra_css:
  - stylesheets/extra.css


# Extensions
markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {}
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true


plugins:
  - search


extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.bootcdn.net/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.min.js
  # - javascripts/analytics.js


extra:
  copyright: <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a>
  generator: false



