name: ci

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      # 设置 Python 环境
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # 设置缓存 ID
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      # 安装 mkdocs-material
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force

  sync:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Copy files to new repo
        run: |
          git clone https://${{ secrets.PAT_TOKEN }}@github.com/Jerremiz/scnu-sw-online.git scnu-sw-online
          cp -r * scnu-sw-online
          cd scnu-sw-online
          git add .
          git commit -m "Sync from source repo gh-pages"
          git push origin main
