name: sync

on:
  workflow_run:
    workflows:
      - deploy
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        ref: gh-pages
    
    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://github.com/MyRepo/project.git
    
    - name: Add destination repository
      run: git remote add destination https://github.com/Jerremiz/scnu-sw-online.git
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    
    - name: Push
      run: |
        git push destination gh-pages:main --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
